global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'carryconnect-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['carryconnect-api:8081']
        labels:
          application: 'CarryConnect API'
          environment: 'development'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
